name: iOS CI Pipeline

on:
  push:
    branches: [ "main" ]

env:
  SCHEME: "iOSQEDemo"
  DEVICE: "iPhone 16"

jobs:
  build:
    name: Build and Test using iPhone 16 simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['schemes'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$SCHEME" -project iOSQEDemo.xcodeproj -destination "platform=iOS Simulator,name=$DEVICE,OS=latest"

      - name: Test
        run: |
          xcodebuild test-without-building -scheme "$SCHEME" -project iOSQEDemo.xcodeproj -destination "platform=iOS Simulator,name=$DEVICE,OS=latest"
