name: iOS CI Pipeline

on:
  push:
    branches: [ "main" ]

env:
  SCHEME: "iOSQEDemo"
  DEVICE: "iPhone 16"
  PLATFORM: "iOS Simulator"
  OS_VERSION: "18.1"

jobs:
  build:
    name: Build and Test using iPhone 16 simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Boot iPhone 16 Simulator
        run: |
          xcrun simctl shutdown all
          xcrun simctl boot "iPhone 16"
          xcrun simctl list devices

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -scheme "iOSQEDemo" \
            -project iOSQEDemo.xcodeproj \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.1"

      - name: Test
        run: |
          xcodebuild test-without-building \
            -scheme "iOSQEDemo" \
            -project iOSQEDemo.xcodeproj \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.1"
