name: iOS CI Pipeline

on:
  push:
    branches: [ "main" ]

env:
  SCHEME: "iOSQEDemo"
  DEVICE: "iPhone 16"

jobs:
  build:
    name: Build and Test using iPhone 16 simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['schemes'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -project iOSQEDemo.xcodeproj -destination "platform=$platform,name=$DEVICE,OS=latest"

      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild test-without-building -scheme "$scheme" -project iOSQEDemo.xcodeproj -destination "platform=$platform,name=$DEVICE,OS=latest"
