name: iOS CI Pipeline

on:
  push:
    branches: [ "main" ]

env:
  SCHEME: "iOSQEDemo"
  DEVICE: "iPhone 16"
  PLATFORM: "iOS Simulator"
  OS_VERSION: "18.2"

jobs:
  build:
    name: Build and Test using iPhone 16 simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Create iPhone 16 Simulator
        run: |
          xcrun simctl delete "iOSQEDemo-iPhone-16" || true
          xcrun simctl create "iOSQEDemo-iPhone-16" com.apple.CoreSimulator.SimDeviceType.iPhone-16 com.apple.CoreSimulator.SimRuntime.iOS-18-2
          xcrun simctl boot "iOSQEDemo-iPhone-16"
          xcrun simctl list devices

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -scheme "$SCHEME" \
            -project iOSQEDemo.xcodeproj \
            -destination "platform=$PLATFORM,name=$DEVICE,OS=$OS_VERSION"

      - name: Test
        run: |
          xcodebuild test-without-building \
            -scheme "$SCHEME" \
            -project iOSQEDemo.xcodeproj \
            -destination "platform=$PLATFORM,name=$DEVICE,OS=$OS_VERSION"
