name: iOS CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-tests:
    name: Build and Run Unit Tests
    runs-on: macos-14

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install Dependencies
        run: |
          sudo gem install cocoapods xcpretty
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "⚠️ No Podfile found, skipping CocoaPods installation."
          fi

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json)
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['schemes'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Run Unit Tests
        env:
          scheme: ${{ 'default' }}
        run: |
          device="iPhone 14"
          xcodebuild build-for-testing -scheme "$scheme" -destination "platform=iOS Simulator,name=$device,OS=latest"
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=iOS Simulator,name=$device,OS=latest" | xcpretty --test --report junit

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: UnitTestResults
          path: test-output/

  ui-tests:
    name: Build and Run UI Tests
    runs-on: macos-14
    needs: unit-tests

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install Dependencies
        run: |
          sudo gem install cocoapods xcpretty
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "⚠️ No Podfile found, skipping CocoaPods installation."
          fi

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json)
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['schemes'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build for UI Testing
        env:
          scheme: ${{ 'default' }}
        run: |
          device="iPhone 14"
          xcodebuild build-for-testing -scheme "$scheme" -destination "platform=iOS Simulator,name=$device,OS=latest"

      - name: Run UI Tests
        run: |
          device="iPhone 14"
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=iOS Simulator,name=$device,OS=latest" | xcpretty --test --report junit

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: UITestResults
          path: test-output/
